FROM centos:latest
RUN yum install epel-release -y
RUN yum update -y
RUN yum install python36 -y

RUN python3.6 -m venv keras-env

#Install Dependencies:

RUN source keras-env/bin/activate && pip install --upgrade pip
RUN source keras-env/bin/activate install --upgrade setuptool
RUN source keras-env/bin/activate && pip install numpy scipy scikit-learn pillow h5py

RUN source keras-env/bin/activate && pip install tensorflow
RUN source keras-env/bin/activate && pip install keras
RUN source keras-env/bin/activate && pip install pandas



